### ISSUE TITLE
Deprecation warning when building Cantera with Python 3.10

### ISSUE THREAD

**Issue by mefuller** [Cantera/cantera#1114]
**Problem description**
When building Cantera (fully updated Fedora Linux 35 (beta)) with Python 3.10, the following deprecation warning is issued:
`<string>:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives`
`<string>:1: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead`

**Steps to reproduce**
`scons build` with python 3.10

**Behavior**

Building is unaffected at present

**System information**

- Cantera version: commit a27eb1fff413beddf6d64d013a0ceb4dc08b4139
- OS: Fedora Linux 35 (beta)
- Python/MATLAB/other software versions: Python 3.10

**Comment by bryanwweber** [comment]
This is resolved by #1075 which removes the use of `distutils`.

**Comment by ischoegl** [comment]
@bryanwweber … would it be possible to separate the fix for this out? #1075 is still not marked as ready for review and it’s not clear what plans are in terms of splitting the build process etc.

**Comment by bryanwweber** [comment]
@ischoegl looks like I forgot to request a review. The PR has been ready since August 😕

**Comment by speth** [comment]
This is fixed now that #1075 has been merged.
